# Generated by Django 5.0.4 on 2024-05-18 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGN', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='annee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnnneeAcademiques', to='SGN.anneeacademique'),
        ),
        migrations.AlterUniqueTogether(
            name='cours',
            unique_together={('code',)},
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('etudiant', 'classe')},
        ),
    ]
