# Generated by Django 5.0.4 on 2024-05-18 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGN', '0003_remove_uniteenseignement_filiere_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniteenseignement',
            name='option',
        ),
        migrations.AddField(
            model_name='uniteenseignement',
            name='classe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Classes', to='SGN.classe'),
            preserve_default=False,
        ),
    ]
