# Generated by Django 5.0.4 on 2024-05-20 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SGN', '0004_remove_uniteenseignement_option_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('option', 'annee_academique', 'niveau')},
        ),
        migrations.AlterUniqueTogether(
            name='filiere',
            unique_together={('nom', 'code')},
        ),
    ]
