# Generated by Django 5.0.4 on 2024-05-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SGN', '0005_alter_classe_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('nom', 'filiere')},
        ),
    ]
