# Generated by Django 5.0.4 on 2024-05-20 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SGN', '0006_alter_option_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='anneeacademique',
            unique_together={('date_debut', 'date_fin')},
        ),
        migrations.AlterUniqueTogether(
            name='cours',
            unique_together={('code', 'nom')},
        ),
        migrations.AlterUniqueTogether(
            name='departement',
            unique_together={('nom',)},
        ),
        migrations.AlterUniqueTogether(
            name='elementconstitutif',
            unique_together={('code', 'nom')},
        ),
        migrations.AlterUniqueTogether(
            name='enseignant',
            unique_together={('nom', 'prenom', 'photo')},
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('annee', 'semestre')},
        ),
        migrations.AlterUniqueTogether(
            name='uniteenseignement',
            unique_together={('code', 'nom')},
        ),
    ]
