# Generated by Django 5.0.4 on 2024-05-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGN', '0007_alter_anneeacademique_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='saisie',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
